[package]
name = "pdf_from_json"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.4"
indicatif = "0.17.8"
printpdf = "0.7.0"
reqwest = {version = "0.12.8", features = ["blocking"]}
serde = {version = "1.0.213", features = ["serde_derive"]}
serde_json = "1.0.132"
